version: '3.8'

services:
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=auth_user
      - DB_PASSWORD=auth_password
      - DB_NAME=auth_db
      - JWT_SECRET=ilovemilfsbro
      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=ilovemilfsbro
    ports:
      - "8081:8081"
    depends_on:
      - db
      - auth

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: